"""V1.1 durable interview schema

Revision ID: 0001
Revises:
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("revoked_at", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_subject_id"), ["subject_id"], unique=False)

    op.create_table(
        "budget_reservations",
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("amount_micro", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("budget_reservations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budget_reservations_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_budget_reservations_month"), ["month"], unique=False)
        batch_op.create_index(batch_op.f("ix_budget_reservations_session_id"), ["session_id"], unique=False)

    op.create_table(
        "idempotency_requests",
        sa.Column("scope", sa.String(length=250), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key"),
    )
    with op.batch_alter_table("idempotency_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_idempotency_requests_session_id"), ["session_id"], unique=False)

    op.create_table(
        "owner_accounts",
        sa.Column("singleton", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("singleton"),
    )
    op.create_table(
        "request_limits",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("window", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "studies",
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("current_version_id", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usage_ledger",
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=200), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("amount_micro", sa.Integer(), nullable=True),
        sa.Column("amount_source", sa.String(length=16), nullable=False),
        sa.Column("price_snapshot", sa.JSON(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_ledger", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_ledger_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_ledger_month"), ["month"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_ledger_session_id"), ["session_id"], unique=False)

    op.create_table(
        "study_versions",
        sa.Column("study_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("retention", sa.String(length=16), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint("retention = 'permanent'", name="study_permanent"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "number"),
    )
    with op.batch_alter_table("study_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_versions_study_id"), ["study_id"], unique=False)

    op.create_table(
        "invites",
        sa.Column("study_version_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("redeemed_at", sa.Float(), nullable=True),
        sa.Column("revoked_at", sa.Float(), nullable=True),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_version_id"],
            ["study_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "sessions",
        sa.Column("study_id", sa.String(length=32), nullable=False),
        sa.Column("study_version_id", sa.String(length=32), nullable=False),
        sa.Column("participant_code", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("consent_version", sa.String(length=64), nullable=True),
        sa.Column("processing_consent", sa.Boolean(), nullable=False),
        sa.Column("permanent_consent", sa.Boolean(), nullable=False),
        sa.Column("retention", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("active_seconds", sa.Float(), nullable=False),
        sa.Column("last_heartbeat", sa.Float(), nullable=True),
        sa.Column("target_seconds", sa.Integer(), nullable=False),
        sa.Column("budget_micro", sa.Integer(), nullable=False),
        sa.Column("spent_micro", sa.Integer(), nullable=False),
        sa.Column("reserved_micro", sa.Integer(), nullable=False),
        sa.Column("pause_reason", sa.String(length=64), nullable=True),
        sa.Column("ended_at", sa.Float(), nullable=True),
        sa.Column("end_reason", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("memory_version", sa.Integer(), nullable=False),
        sa.Column("price_snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_version_id"],
            ["study_versions.id"],
        ),
        sa.CheckConstraint("retention = 'permanent' AND expires_at IS NULL", name="session_permanent"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_study_id"), ["study_id"], unique=False)

    op.create_table(
        "consents",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("processing", sa.Boolean(), nullable=False),
        sa.Column("permanent", sa.Boolean(), nullable=False),
        sa.Column("retention", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consents_session_id"), ["session_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("lease_token", sa.String(length=32), nullable=True),
        sa.Column("call_started", sa.Boolean(), nullable=False),
        sa.Column("next_run", sa.Float(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "memory_snapshots",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("through_seq", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "version"),
    )
    with op.batch_alter_table("memory_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_snapshots_session_id"), ["session_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_updated", sa.Boolean(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "version"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_session_id"), ["session_id"], unique=False)

    op.create_table(
        "session_events",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq"),
    )
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_events_session_id"), ["session_id"], unique=False)

    op.create_table(
        "turns",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("input_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision_id", sa.String(length=32), nullable=True),
        sa.Column("audio_asset_id", sa.String(length=32), nullable=True),
        sa.Column("mime_type", sa.String(length=80), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("topic_id", sa.String(length=64), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("played_complete", sa.Boolean(), nullable=True),
        sa.Column("start_seconds", sa.Float(), nullable=True),
        sa.Column("end_seconds", sa.Float(), nullable=True),
        sa.Column("finalized_chunks", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq"),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turns_session_id"), ["session_id"], unique=False)

    op.create_table(
        "audio_assets",
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("turn_id", sa.String(length=32), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("retention", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("segments", sa.JSON(), nullable=False),
        sa.CheckConstraint("retention = 'permanent' AND expires_at IS NULL", name="asset_permanent"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audio_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audio_assets_session_id"), ["session_id"], unique=False)

    op.create_table(
        "transcript_revisions",
        sa.Column("turn_id", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("editor", sa.String(length=32), nullable=False),
        sa.Column("previous_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transcript_revisions_turn_id"), ["turn_id"], unique=False)

    op.create_table(
        "upload_chunks",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("turn_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id", "seq"),
    )
    with op.batch_alter_table("upload_chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_upload_chunks_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_upload_chunks_turn_id"), ["turn_id"], unique=False)

    op.create_table(
        "report_citations",
        sa.Column("report_id", sa.String(length=32), nullable=False),
        sa.Column("revision_id", sa.String(length=32), nullable=False),
        sa.Column("turn_id", sa.String(length=32), nullable=False),
        sa.Column("start", sa.Integer(), nullable=False),
        sa.Column("end", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["transcript_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_citations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_citations_report_id"), ["report_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_citations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_citations_report_id"))

    op.drop_table("report_citations")
    with op.batch_alter_table("upload_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_chunks_turn_id"))
        batch_op.drop_index(batch_op.f("ix_upload_chunks_session_id"))

    op.drop_table("upload_chunks")
    with op.batch_alter_table("transcript_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_revisions_turn_id"))

    op.drop_table("transcript_revisions")
    with op.batch_alter_table("audio_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_assets_session_id"))

    op.drop_table("audio_assets")
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turns_session_id"))

    op.drop_table("turns")
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_events_session_id"))

    op.drop_table("session_events")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_session_id"))

    op.drop_table("reports")
    with op.batch_alter_table("memory_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_snapshots_session_id"))

    op.drop_table("memory_snapshots")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_session_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_session_id"))

    op.drop_table("consents")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_study_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_status"))

    op.drop_table("sessions")
    op.drop_table("invites")
    with op.batch_alter_table("study_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_versions_study_id"))

    op.drop_table("study_versions")
    with op.batch_alter_table("usage_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_ledger_session_id"))
        batch_op.drop_index(batch_op.f("ix_usage_ledger_month"))
        batch_op.drop_index(batch_op.f("ix_usage_ledger_job_id"))

    op.drop_table("usage_ledger")
    op.drop_table("studies")
    op.drop_table("request_limits")
    op.drop_table("owner_accounts")
    with op.batch_alter_table("idempotency_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_requests_session_id"))

    op.drop_table("idempotency_requests")
    with op.batch_alter_table("budget_reservations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_reservations_session_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_month"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_job_id"))

    op.drop_table("budget_reservations")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_subject_id"))

    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
